server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://111.231.145.185:30002/mysql?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: blue123456
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /**
file:
  upload:
    root: /upload
    tempRoot: /upload/temp
xmlDir: /Users/upload/createdb
datasource:
#  url:  111.231.145.185:30002
#  username: root
#  password: blue123456
  url:  192.168.31.39:3306
  username:
  password:
  driver: /opt/mysql-connector-java-5.1.21.jar
controllerTemplate: BackController.ftl
searchTemplate: Search.ftl
modelRootClass: BaseTimeDoMain







debug: true














