server:
  port: 8089
spring:
  datasource:
#    url:  jdbc:mysql://a.nbrc.cn:20006/mysql?usessl=true&useunicode=true
#    username: root
#    password: blue@123
    url:  jdbc:mysql://rm-uf6wz809tr8obfsfjxo.mysql.rds.aliyuncs.com:27113/test_youyu_db?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: test_blue
    password: blue123456
    driver-class-name:  com.mysql.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /**
file:
  upload:
    root: /upload
    tempRoot: /upload/temp
xmlDir: /Users/upload/createdb
datasource:
#  url:  a.nbrc.cn:20006
#  username: root
#  password: blue@123
  url:  rm-uf6wz809tr8obfsfjxo.mysql.rds.aliyuncs.com:27113
  username: test_blue
  password: blue123456
  driver: /opt/mysql-connector-java-5.1.21.jar
controllerTemplate: BackController.ftl
searchTemplate: Search.ftl
modelRootClass: BaseTimeDoMain







debug: true














