server:
  port: 8089
spring:
  datasource:
    url:  jdbc:mysql://a.nbrc.cn:13306/mysql?useSSL=false&useUnicode=true
    username: root
    password: nbrc@123
    driver-class-name:  com.mysql.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /**
file:
  upload:
    root: /Users/upload
    tempRoot: /Users/upload/temp
xmlDir: /opt/create-db-file
datasource:
  url:  a.nbrc.cn:13306
  username: root
  password: nbrc@123
  driver: /opt/mysql-connector-java-5.1.21.jar
controllerTemplate: RestfulController.ftl
searchTemplate: SourceSearch.ftl
modelRootClass: BaseSourceDoMain



debug: true














