server:
  port: 8089
spring:
  datasource:
#    url:  jdbc:mysql://127.0.0.1:3306/mysql?useSSL=true&useUnicode=true
#   # url:  jdbc:mysql://10.19.151.71:8000/mysql?useSSL=false&useUnicode=true
#    username: root
#    password: 123456
#    #password: W7sjb1G_%Jpl
#    driver-class-name:  com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.110.9:53306/sophon_sharing?autoReconnect=true&useSSL=false # todo
#    username: root
#    password: 4QrcOUm6Wau+VuBX8g+IPg==
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.110.9:5432/sophon_sharing_video?stringtype=unspecified&currentSchema=dictory,public,geo
    username: postgres
    password: skzz@123
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /**

  freemarker:
    settings:
      classic_compatible: true
file:
  upload:
    root: /Users/upload
    tempRoot: /Users/upload/temp
xmlDir: /Users/upload/createdb
datasource:
  url:  127.0.0.1:3306
  username: root
  password: 123456
  driver: /Users/upload/createdb/lib/mysql-connector-java-5.1.20-bin.jar
controllerTemplate: BackController.ftl
searchTemplate: Search.ftl
modelRootClass: BaseTimeDoMain







debug: true














