server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://183.249.87.107:5433/sophon_sharing_video?currentSchema=dictory,public,geo
    username: postgres
    password: skzz@123
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /**
file:
  upload:
    root: /Users/upload
    tempRoot: /Users/upload/temp
xmlDir: /Users/upload/createdb
datasource:
  url: jdbc:postgresql://183.249.87.107:5433
  username: postgres
  password: skzz@123
  driver: D:\project\.m2\repository\org\postgresql\postgresql\42.2.12\postgresql-42.2.12.jar
controllerTemplate: BackController.ftl
searchTemplate: Search.ftl
modelRootClass: BaseTimeDoMain







debug: true






logging:
  level:
    root: info
    vip.sunke: debug
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /www/create-code-xy/logs/front.log
  file.max-size: 200MB







